# Generated by Django 2.1.5 on 2019-02-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deals',
            fields=[
                ('id', models.AutoField(db_column='deals_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='deals_name', default=0, max_length=256)),
                ('url', models.CharField(db_column='deals_url', default=0, max_length=512)),
                ('image', models.CharField(db_column='deals_image', default=0, max_length=512)),
                ('mrp', models.DecimalField(db_column='deals_mrp', decimal_places=2, default=0, max_digits=6)),
                ('price', models.DecimalField(db_column='deals_price', decimal_places=2, default=0, max_digits=6)),
                ('storeimage', models.CharField(db_column='deals_store_image', default=0, max_length=512)),
            ],
        ),
    ]
