# Generated by Django 2.1.5 on 2019-02-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='mrp',
            field=models.CharField(db_column='deals_mrp', default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='deals',
            name='price',
            field=models.CharField(db_column='deals_price', default=0, max_length=256),
        ),
    ]
